jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

notifications:
  email:
    on_success: never
    on_failure: change
    
script: mvn integration-test -B -V
