jdk:
  - oraclejdk8

addons:
  hostname: tanaga
  apt:
    packages:
      - oracle-java8-installer

language: java

notifications:
  email:
    on_success: never
    on_failure: change
    
script: mvn integration-test -B -V -Dhost=tanaga -DconfigLocation=../../common/org.jcommand.cm.persistencemanager/config
