jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

notifications:
  email:
    on_success: never
    on_failure: change
    
script: bundle exec mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && bundle exec mvn integration-test -B -V