package org.jcommand.queue.capability.service;

import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.osgi.framework.wiring.BundleCapability;
import org.prevayler.SureTransactionWithQuery;

class SaveCapability implements SureTransactionWithQuery<CapabilityRoot, Boolean> {
	/**
	 * auto generated by eclipse 4.6
	 */
	private static final long serialVersionUID = 5042733252315464821L;
	private BundleCapability capability;
	private Long queueId;

	SaveCapability(Long queueId, BundleCapability capability){
		this.queueId = queueId;
		this.capability = capability;
	}
	
	@Override
	public Boolean executeAndQuery(CapabilityRoot root, Date date) {
		Map<Long, Set<BundleCapability>> repository = root.repository;
		if(!root.repository.containsKey(queueId)){
			repository.put(queueId, new HashSet<BundleCapability>(100));
		}
		repository.get(queueId).add(capability);
		
		return Boolean.TRUE;
	}
}