package org.jcommand.queue.manager.capability;

import java.util.Date;
import java.util.Set;

import org.osgi.framework.wiring.BundleCapability;
import org.prevayler.SureTransactionWithQuery;

class SaveCapability implements SureTransactionWithQuery<CapabilityRoot, Boolean> {
	/**
	 * auto generated by eclipse 4.6
	 */
	private static final long serialVersionUID = 5042733252315464821L;
	private BundleCapability capability;

	SaveCapability(BundleCapability capability) {
		this.capability = capability;
	}

	@Override
	public Boolean executeAndQuery(CapabilityRoot root, Date date) {
		Set<BundleCapability> repository = root.repository;
		return repository.add(capability);
	}
}